collegesite/collegepjt/collegeapp/urls.py
from . import views
from django.urls import path

urlpatterns = [

    path('',views.index,name='index'),
    path('home', views.home, name='home'),
    path('details', views.details, name='details'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),
    path('order', views.order, name='order'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('computer',views.computer,name='computer'),
    path('commerce',views.commerce,name='commerce'),
    path('maths',views.maths,name='maths'),
    path('science',views.science,name='science'),
]

collegesite/collegepjt/collegepjt/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from collegepjt import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('collegeapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collegesite/collegepjt/collegeapp/models.py
from django.db import models

# Create your models here.
class department(models.Model):
    dept=models.CharField(max_length=200)

    def __str__(self):
        return self.dept

class courses(models.Model):
    dept=models.ForeignKey(department,on_delete=models.CASCADE)
    course=models.CharField(max_length=200)

    def __str__(self):
        return self.course

class student(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField(null=True, blank=True)
    age = models.IntegerField()
    phone=models.CharField(max_length=15)
    address=models.TextField(max_length=250)
    email=models.EmailField(max_length=250)
    dept = models.ForeignKey(department, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(courses, on_delete=models.SET_NULL, null=True)
    purpose = models.CharField(max_length=20)

collegesite/collegepjt/collegeapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from.models import department
from.models import courses
# Create your views here.
def index(request):
    return render(request,"index.html")

def computer(request):
    return render(request,"computer.html")

def commerce(request):
    return render(request,"commerce.html")

def maths(request):
    return render(request,"maths.html")

def science(request):
    return render(request,"science.html")

def home(request):
    return render(request,"index.html")

def portfolio(request):
    return render(request,"portfolio.html")

def details(request):
    dept=department.objects.all()

    return render(request,"details.html",{'depart':dept})

def load_courses(request):
    department_id = request.GET.get('department')
    course = courses.objects.filter(dept_id=department_id)
    for i in course:
        print(i)
    return render(request,'course_list.html',{'courses': course})


def order(request):
    msg=messages.info(request,"Order Confirmed")
    return redirect('details')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('portfolio')
        else:
            messages.info(request,'Invalid credentials')
            return redirect('login')
    return render(request,'login.html')

def register(request):
    if request.method=='POST':
        username=request.POST['username']

        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request," Username already taken")
                return redirect('register')

            else:
                user=User.objects.create_user(username=username,password=password)
                user.save()
                return redirect('login')
        else:
            messages.info(request," Password mismatch")
            return redirect("register")
        return redirect('/')
    return render(request,'register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

collegesite/collegepjt/templates/commerce.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commerce</title>
</head>
<body>
<body style="background-image:url('{% static 'assets/images/commerce.jpeg' %}'); background-repeat: no-repeat;background-attachment: fixed;
  background-size: cover; ">
<h1 style="text-align:center;"><b>Commerce</b></h1>
<p style="text-align:center;"><h3>
    Commerce is the large-scale organized system of activities, functions, procedures and institutions
directly and indirectly related to the exchange (buying and selling) of goods and services among two
or more parties within local, regional, national or international economies.[1] More specifically, commerce
is not business, but rather the part of business which facilitates the movement and distribution of finished

or unfinished but valuable goods and services from the producers to the end consumers on a large scale, as
opposed to the sourcing of raw materials and manufacturing of those goods. Commerce is subtly different from

trade as well, which is the final transaction, exchange or transfer of finished goods and services between a

seller and an end consumer. Commerce not only includes trade as defined above, but also a series of transactions
that happen between the producer and the seller with the help of the auxiliary services and means which facilitate such trade.
These auxiliary services include transportation, communication, warehousing, insurance, banking, financial markets,
advertising, packaging, the services of commercial agents and agencies, etc. In other words, commerce encompasses a wide
array of political, economical, technological, logistical, legal, regulatory, social and cultural aspects of trade on a
large scale. From a marketing perspective, commerce creates time and place utility by making goods and services available
to the customers at the right place and at the right time by changing their location or placement.
Described in this manner, trade is a part of commerce and commerce is a part of business.

</h3></p>
<a href="home"> <h3 style="text-align:right;">Go to home page</h3></a>
</body>
</html>

collegesite/collegepjt/templates/computer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Computer Science</title>
</head>
<body style="background-image:url('{% static 'assets/images/computer.jpg' %}'); background-repeat: no-repeat;background-attachment: fixed;
  background-size: cover; ">
<h1 style="text-align:center;"><b>Computer Science</b></h1>
<p style="text-align:center;"><h3>Computer science is the study of computation, automation, and information. Computer science spans
    theoretical disciplines (such as algorithms, theory of computation, information theory, and automation) to
    practical disciplines (including the design and implementation of hardware and software).Computer science
    is generally considered an academic discipline and distinct from computer programming which is considered to be a
    technical field.

Algorithms and data structures are central to computer science. The theory of computation
    concerns abstract models of computation and general classes of problems that can be solved using them.
    The fields of cryptography and computer security involve studying the means for secure communication and
    for preventing security vulnerabilities. Computer graphics and computational geometry address the generation
    of images. Programming language theory considers different ways to describe computational processes,
    and database theory concerns the management of repositories of data.</h3></p>
<a href="home" > <h3 style="text-align:right;">Go to home page</h3></a>
</body>
</html>

collegesite/collegepjt/templates/course_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<select><option value="">--------------</option>
{% for i in courses %}
<option value="{{ i.id }}">{{ i.course }}</option>
{% endfor %}
</select>

</body>
</html>

collegesite/collegepjt/templates/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Order</title>
    <style>
a:link, a:visited {
  background-color:red;
  color: black;
  padding: 7px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  border-radius: 4px;
}

<!--a:hover, a:active {-->
<!--  background-color: red;-->
<!--}-->


</style>

</head>
<body style="background-image:url('{% static 'assets/images/store1.jpg' %}'); background-repeat: no-repeat;background-attachment: fixed;
  background-size: cover; ">
<form action="order" id="studentForm" method="post" data-courses-url="{% url 'ajax_load_courses' %}" >
{% csrf_token %}
    <div class="row"> <br></div>
<div class="row">
    <div class="col-md-2">
        <label> Name : </label>
    </div>
    <div class="col-md-2">
       <input type="text" name="name" size="60"/>
    </div>
</div><br>
    <div class="row">
    <div class="col-md-2">
        <label> Date of Birth : </label>
    </div>
    <div class="col-md-2">
       <input type="date" id="dob" name="dob">

    </div>
</div><br>
<div class="row">
    <div class="col-md-2">
        <label> Age : </label>
    </div>
    <div class="col-md-2">
       <input type="text" id="age" name="age">
    </div>
</div><br>
  <div class="row">
    <div class="col-md-2">
        <label> Gender : </label>
    </div>
    <div class="col-md-2">
       <input type="radio" name="gender"/> Male <br>
       <input type="radio" name="gender"/> Female
    </div>
  </div><br>
<div class="row">
    <div class="col-md-2">
        <label> Phone Number : </label>
    </div>
    <div class="col-md-2">
       <input type="text" name="country code"  value="+91" size="2"/>
       <input type="text" name="phone" size="10"/>
    </div></div><br>

<div class="row">
    <div class="col-md-2">
        <label> Address : </label>
    </div>
    <div class="col-md-2">
       <textarea cols="60" rows="5" value="address">
       </textarea>
    </div></div><br>
<div class="row">
    <div class="col-md-2">
        <label> Email : </label>
    </div>
    <div class="col-md-2">
       <input type="email" id="email" name="email"/>
    </div>
</div><br>

 <div class="row">
    <div class="col-md-2">
        <label> Department : </label>
    </div>
    <div class="col-md-2">
        <select id="id_department" >
    <option value="select">Select</option>
    {% for i in depart %}

      <option value="{{i.id}}" >{{i.dept}}</a></option>
            {% endfor %}
    </select>
    </div>
 </div><br>

<div class="row">
    <div class="col-md-2">
        <label> Course : </label>
    </div>
    <div class="col-md-2">
        <select id="id_course" >
       <option value="select" >--------------------</option>
    {% for i in courses %}

               <option value="{{i.id}}">{{i.course}}</option>

    {% endfor %}

</select>
    </div>
 </div><br>


<div class="row">
    <div class="col-md-2">
        <label> Purpose : </label>
    </div>
    <div class="col-md-2">
       <select>
<option value="Select">Select</option>
<option value="enquiry">For Enquiry</option>
<option value="order">Place Order</option>
<option value="return">Return</option>
</select>
    </div>
</div><br>
    <div class="row">
    <div class="col-md-2">
        <label> Materials Provide : </label>
    </div>
    <div class="col-md-3">
     <input type="checkbox" name="material" >Note Book&nbsp;&nbsp;
     <input type="checkbox" name="material" >Pen&nbsp;&nbsp;
     <input type="checkbox" name="material" >Exam papers
    </div>
</div>
    <br>

&nbsp;<br>
        &nbsp;&nbsp; &nbsp;&nbsp;
        <input type="submit" value="Submit" class="btn btn-primary"/>&nbsp;&nbsp;

    <a href="logout">Logout</a> <br><br>
    <div class="row">
       {% for msg in messages %}
           <h5 style="color:blue;">{{msg}}</h5>
       {% endfor %}
    </div>
</form>

</body>
</html>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_department").change(function () {
      var url = $("#studentForm").attr("data-courses-url");
      var departmentId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'department': departmentId
        },
        success: function(data) {
          $("#id_course").html(data);
        }
      });

    });
  </script>

collegesite/collegepjt/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>

	<!-- META ============================================= -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	
	<!-- DESCRIPTION -->
	<meta name="description" content="EduChamp : Education HTML Template" />
	
	<!-- OG -->
	<meta property="og:title" content="EduChamp : Education HTML Template" />
	<meta property="og:description" content="EduChamp : Education HTML Template" />
	<meta property="og:image" content="" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- FAVICONS ICON ============================================= -->
	<link rel="icon" href="{% static 'assets/images/favicon.ico' %}' %}" type="image/x-icon" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}" />
	
	<!-- PAGE TITLE HERE ============================================= -->
	<title>EduChamp : Education HTML Template </title>
	
	<!-- MOBILE SPECIFIC ============================================= -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!--[if lt IE 9]>
	<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
	<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
	
	<!-- All PLUGINS CSS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/assets.css' %}">
	
	<!-- TYPOGRAPHY ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/typography.css' %}">
	
	<!-- SHORTCODES ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/shortcodes/shortcodes.css' %}">
	
	<!-- STYLESHEETS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
	<link class="skin" rel="stylesheet" type="text/css" href="{% static 'assets/css/color/color-1.css' %}">
	
</head>
<body id="bg">
<div class="page-wraper">
	<div id="loading-icon-bx"></div>
	<div class="account-form">
		<div class="account-head" style="background-image:url('{% static 'assets/images/background/bg2.jpg' %}');">
			<a href="index.html"><img src="{% static 'assets/images/logo-white-2.png' %}" alt=""></a>
		</div>
		<div class="account-form-inner">
			<div class="account-container">
				<div class="heading-bx left">
					<h2 class="title-head">Login to your <span>Account</span></h2>
					<p>Don't have an account? <a href="register">Register Now</a></p>
				</div>	
				<form class="contact-bx" action="login" method="post">
					{% csrf_token %}
					<div class="row placeani">
						<div class="col-lg-12">
							<div class="form-group">
								<div class="input-group">
									<label>Username</label>
									<input name="username" type="text" required="" class="form-control">
								</div>
							</div>
						</div>
						<div class="col-lg-12">
							<div class="form-group">
								<div class="input-group"> 
									<label>Password</label>
									<input name="password" type="password" class="form-control" required="">
								</div>
							</div>
						</div>
<!--						{% for msg in messages %}-->
<!--                           <h6 style="color:red;text-align:center;">{{msg}}</h6>-->
<!--                        {% endfor %}-->
					    <br><br>
						<div class="col-lg-12">
							<div class="form-group form-forget">
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input" id="customControlAutosizing">
									<label class="custom-control-label" for="customControlAutosizing">Remember me</label>
								</div>
								<a href="forget-password.html" class="ml-auto">Forgot Password?</a>
							</div>
						</div>
						<div class="col-lg-12 m-b30">
							<button name="submit" type="submit" value="Submit" class="btn button-md">Login</button>
						</div>
<!--						<div class="col-lg-12">-->
<!--							<h6>Login with Social media</h6>-->
<!--							<div class="d-flex">-->
<!--								<a class="btn flex-fill m-r5 facebook" href="#"><i class="fa fa-facebook"></i>Facebook</a>-->
<!--								<a class="btn flex-fill m-l5 google-plus" href="#"><i class="fa fa-google-plus"></i>Google Plus</a>-->
<!--							</div>-->
<!--						</div>-->
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- External JavaScripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap-select/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js' %}"></script>
<script src="{% static 'assets/vendors/magnific-popup/magnific-popup.js' %}"></script>
<script src="{% static 'assets/vendors/counter/waypoints-min.js' %}"></script>
<script src="{% static 'sets/vendors/counter/counterup.min.js' %}"></script>
<script src="{% static 'assets/vendors/imagesloaded/imagesloaded.js' %}"></script>
<script src="{% static 'assets/vendors/masonry/masonry.js' %}"></script>
<script src="{% static 'assets/vendors/masonry/filter.js' %}"></script>
<script src="{% static 'assets/vendors/owl-carousel/owl.carousel.js' %}"></script>
<script src="{% static 'assets/js/functions.js' %}"></script>
<script src="{% static 'assets/js/contact.js' %}"></script>
<script src="{% static 'assets/vendors/switcher/switcher.js' %}"></script>
</body>

</html>

collegesite/collegepjt/templates/maths.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Maths</title>
</head>

<body style="background-image:url('{% static 'assets/images/maths1.jpg' %}'); background-repeat: no-repeat;background-attachment: fixed;
  background-size: cover; ">
<h1 style="text-align:center;"><b>Maths</b></h1>
<p style="text-align:center;"><h3>
    Mathematics is an area of knowledge that includes the topics of numbers, formulas and related structures, shapes and the spaces in which they are contained, and quantities and their changes. These topics are represented in modern mathematics with the major subdisciplines of number theory,[1] algebra,[2] geometry,[1] and analysis,[3][4] respectively. There is no general consensus among mathematicians about a common definition for their academic discipline.

Most mathematical activity involves the discovery of properties of abstract objects and the use of pure reason to prove them. These objects consist of either abstractions from nature or—in modern mathematics—entities that are stipulated to have certain properties, called axioms. A proof consists of a succession of applications of deductive rules to already established results. These results include previously proved theorems, axioms, and—in case of abstraction from nature—some basic properties that are considered true starting points of the theory under consideration.[5]

Mathematics is essential in the natural sciences, engineering, medicine, finance, computer science and the social sciences. Although mathematics is extensively used for modeling phenomena, the fundamental truths of mathematics are independent from any scientific experimentation. Some areas of mathematics, such as statistics and game theory, are developed in close correlation with their applications and are often grouped under applied mathematics. Other areas are developed independently from any application (and are therefore called pure mathematics), but often later find practical applications.[6][7] The problem of integer factorization, for example, which goes back to Euclid in 300 BC, had no practical application before its use in
    the RSA cryptosystem, now widely used for the security of computer networks.
</h3></p>
<a href="home" > <h3 style="text-align:right;">Go to home page</h3></a>

</body>
</html>

collegesite/collegepjt/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<!-- META ============================================= -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	
	<!-- DESCRIPTION -->
	<meta name="description" content="EduChamp : Education HTML Template" />
	
	<!-- OG -->
	<meta property="og:title" content="EduChamp : Education HTML Template" />
	<meta property="og:description" content="EduChamp : Education HTML Template" />
	<meta property="og:image" content="" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- FAVICONS ICON ============================================= -->
	<link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}" />
	
	<!-- PAGE TITLE HERE ============================================= -->
	<title>EduChamp : Education HTML Template </title>
	
	<!-- MOBILE SPECIFIC ============================================= -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!--[if lt IE 9]>
	<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
	<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
	
	<!-- All PLUGINS CSS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/assets.css' %}">
	
	<!-- TYPOGRAPHY ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/typography.css' %}">
	
	<!-- SHORTCODES ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/shortcodes/shortcodes.css' %}">
	
	<!-- STYLESHEETS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
	<link class="skin" rel="stylesheet" type="text/css" href="{% static 'assets/css/color/color-1.css' %}">
	
</head>
<body id="bg">
<div class="page-wraper">
	<div id="loading-icon-bx"></div>
	<div class="account-form">
		<div class="account-head" style="background-image:url('{% static 'assets/images/background/bg2.jpg' %}');">
			<a href="index.html"><img src="{% static 'assets/images/logo-white-2.png' %}" alt=""></a>
		</div>
		<div class="account-form-inner">
			<div class="account-container">
				<div class="heading-bx left">
					<h2 class="title-head">Sign Up <span>Now</span></h2>
					<p>Login Your Account <a href="login">Click here</a></p>
				</div>	
				<form class="contact-bx" action="register" method="post">
					{% csrf_token %}
					<div class="row placeani">
						<div class="col-lg-12">
							<div class="form-group">
								<div class="input-group">
									<label>Username</label>
									<input name="username" type="text" required="" class="form-control">
								</div>
							</div>
						</div>
						<div class="col-lg-12">
							<div class="form-group">
								<div class="input-group">
									<label>Password</label>
									<input name="password" type="password" required="" class="form-control">
								</div>
							</div>
						</div>
						<div class="col-lg-12">
							<div class="form-group">
								<div class="input-group"> 
									<label> Confirm Password</label>
									<input name="password1" type="password" class="form-control" required="">
								</div>
							</div>
						</div>
						{% for msg in messages %}
                            <h6 style="color:red;text-align:center;">{{msg}}</h6>
                        {% endfor %}
					    <br><br>
						<div class="col-lg-12 m-b30">
							<button name="submit" type="submit" value="Submit" class="btn button-md">Register</button>
						</div>
<!--						<div class="col-lg-12">-->
<!--							<h6>Sign Up with Social media</h6>-->
<!--							<div class="d-flex">-->
<!--								<a class="btn flex-fill m-r5 facebook" href="#"><i class="fa fa-facebook"></i>Facebook</a>-->
<!--								<a class="btn flex-fill m-l5 google-plus" href="#"><i class="fa fa-google-plus"></i>Google Plus</a>-->
<!--							</div>-->
<!--						</div>-->
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- External JavaScripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap-select/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js' %}"></script>
<script src="{% static 'assets/vendors/magnific-popup/magnific-popup.js' %}"></script>
<script src="{% static 'assets/vendors/counter/waypoints-min.js' %}"></script>
<script src="{% static 'assets/vendors/counter/counterup.min.js' %}"></script>
<script src="{% static 'assets/vendors/imagesloaded/imagesloaded.js' %}"></script>
<script src="{% static 'assets/vendors/masonry/masonry.js' %}"></script>
<script src="{% static 'assets/vendors/masonry/filter.js' %}"></script>
<script src="{% static 'assets/vendors/owl-carousel/owl.carousel.js' %}"></script>
<script src="{% static 'assets/js/functions.js' %}"></script>
<script src="{% static 'assets/js/contact.js' %}"></script>
<script src="{% static 'assets/vendors/switcher/switcher.js' %}"></script>
</body>

</html>

collegesite/collegepjt/templates/science.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Science</title>
</head>

<body style="background-image:url('{% static 'assets/images/science.jpg' %}'); background-repeat: no-repeat;background-attachment: fixed;
  background-size: cover; ">
<h1 style="text-align:center;"><b>Science</b></h1>
<p style="text-align:center;"><h3>
    Science is a systematic endeavor that builds and organizes knowledge in the form of testable explanations and predictions
    about the universe.[1][2]

The earliest written records of identifiable predecessors to modern science come from Ancient Egypt and Mesopotamia from around 3000 to 1200 BCE. Their contributions to mathematics, astronomy, and medicine entered and shaped the Greek natural philosophy of classical antiquity, whereby formal attempts were made to provide explanations of events in the physical world based on natural causes.[3]: 12 [4] After the fall of the Western Roman Empire, knowledge of Greek conceptions of the world deteriorated in Western Europe during the early centuries (400 to 1000 CE) of the Middle Ages,
    but was preserved in the Muslim world during the Islamic Golden Age and later by the efforts of Byzantine Greek scholars who brought Greek manuscripts from the dying Byzantine Empire to Western Europe in the Renaissance.

The recovery and assimilation of Greek works and Islamic inquiries into Western Europe from the 10th to 13th century revived "natural philosophy",[6][7] which was later transformed by the Scientific Revolution that began in the 16th century[8] as new ideas and discoveries departed from previous Greek conceptions and traditions.[9][10] The scientific method soon played a greater role in knowledge creation and it was not until the 19th century that many of the institutional and professional features of science began to take shape,along with the changing of "natural philosophy" to "natural science".
</h3></p>
<a href="home" > <h3 style="text-align:right;">Go to home page</h3></a>

</body>
</html>